module.exports = [
  'Acc. Chem. Res.',
  'Acta Crystallogr.',
  'ACS Symp. Ser.',
  'Adv. Synth. Cat.',
  'Adv. Synth. Catal.',
  'Anal. Chim. Acta',
  'Anal. Biochem.',
  'Anal. Chem.',
  'Anal. Commun.',
  'Angew. Chem.',
  'Angew. Chem. Int. Ed. Engl.',
  'Annu. Rev. Biochem.',
  'Annu. Rev. Mater. Sci.',
  'Annu. Rev. Phys. Chem.',
  'Arch. Biochem. Biophys.',
  'Asian J. Org. Chem.',
  'Beilstein J. Org. Chem.',
  'Biochem. Biophys. Res. Commun.',
  'Biochemistry',
  'Biochim. Biophys. Acta',
  'Biophys. J.',
  'Biopolymers',
  'Bull. Chem. Soc. Jpn.',
  'Can. J. Chem.',
  'Cell',
  'Chem. Asian J.',
  'Chem. Ber.',
  'ChemCatChem',
  'Chem. Commun.',
  'Chem. Eur. J.',
  'Chem. Lett.',
  'Chem. Phys. Lett.',
  'Chem. Res. Toxicol.',
  'Chem. Rev.',
  'Chem. Sci.',
  'Chem. Biol.',
  'Chem. Mat.',
  'Coord. Chem. Rev.',
  'Curr. Opin. Struct. Biol.',
  'Dalton Trans.',
  'EMBO J.',
  'Environ. Sci. Technol.',
  'Eur. Biophys. J.',
  'Eur. J. Inorg. Chem.',
  'Eur. J. Org. Chem.',
  'FEBS Lett.',
  'Helv. Chim. Acta',
  'Heteroatom Chem.',
  'Heterocycles',
  'Inorg. Chem.',
  'Inorg. Chim. Acta',
  'Inorg. Synth.',
  'J. Agri. Food Chem.',
  'J. Anal. At. Spectrom.',
  'J. Anal. Chem.',
  'J. Biol. Chem.',
  'J. Biomol. Struct. Dyn.',
  'J. Chem. Educ.',
  'J. Chem. Phys.',
  'J. Chromatogr.',
  'J. Environ. Qual.',
  'J. Fluorine Chem.',
  'J. Inorg. Biochem.',
  'J. Magn. Reson.',
  'J. Med. Chem.',
  'J. Mol. Biol.',
  'J. Mol. Evol.',
  'J. Natl. Cancer Inst.',
  'J. Organomet. Chem.',
  'J. Org. Chem.',
  'J. Phys. Chem. A',
  'J. Phys. Chem. B',
  'J. Phys. Org. Chem.',
  'J. Am. Chem. Soc.',
  'J. Chem. Soc., Chem. Commun.',
  'J. Chem. Soc., Dalton Trans.',
  'J. Chem. Soc., Faraday Trans.',
  'J. Chem. Soc., Perkin Trans. 1',
  'J. Chem. Soc., Perkin Trans. 2',
  'J. Synth. Org. Chem. Jpn.',
  'Langmuir',
  'Methods Enzymol.',
  'Nature',
  'Naturforsch.',
  'Nuc. Acids Res.',
  'Org. Lett.',
  'Organometallics',
  'Phosphorus, Sulfur, and Silicon',
  'Phys. Rev. B',
  'Rev. Lett. A',
  'Rev. Lett. B',
  'Polyhedron',
  'Proc. Nat. Acad. Sci.',
  'Proc. Natl. Acad. Sci.',
  'Prot. Sci.',
  'Proteins',
  'Science',
  'Structure',
  'Struct. Biol.',
  'Synlett',
  'Synthesis',
  'Tetrahedron',
  'Tetrahedron: Asymmetry',
  'Tetrahedron Lett.'
];
